services:
  post-db:
    image: "${POSTGRES_IMAGE}"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - ${DOCKER_NETWORK_NAME}

volumes:
  pgdata:


networks:
  internal:
    external: true
    name: ${DOCKER_NETWORK_NAME}
