### Get existing posts
GET http://localhost:8000/posts
Accept: application/json

### Create new post
POST http://localhost:8000/posts
Content-Type: application/json

{
    "title": "New Post",
    "content": "This is the content of the new post",
    "published": true,
    "rating": 5
}

### Get post by id
GET http://localhost:8000/posts/bc262ac5-166a-4150-a64c-2e40b06e613e
Accept: application/json

### Update post by id
PATCH http://localhost:8000/posts/bc262ac5-166a-4150-a64c-2e40b06e613e
Content-Type: application/json  

{
    "title": "Updated Post",
    "content": "This is the updated content of the post",
    "published": false,
    "rating": 4
}

### Delete post by id
DELETE http://localhost:8000/posts/5cd60fb2-8645-4766-ac41-c0776bf33911
Accept: application/json

###