@JWT = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYjNjMWE3ZTItNGY4ZC00YTFlLTljMmQtNWU2ZjdhOGI5YzBkIiwiZXhwIjoxNzYwNjEyOTI4fQ.ALIPU9nq-9N9ROo8HJZDp6I_7BMwIo0AY8MKY8Au2zw
@POST_ID = e2f1c3b4-5d6e-7a8b-9c0d-1e2f3a4b5c6d

### Vote a post
POST http://localhost:8000/votes/
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
    "post_id": "{{POST_ID}}",
    "vote_direction": 1
}

### Remove vote for a post
POST http://localhost:8000/votes/
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
    "post_id": "{{POST_ID}}",
    "vote_direction": 0
}